# Generated by Django 2.2.12 on 2020-07-29 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('text', models.TextField(verbose_name='Texto')),
                ('post_date', models.TimeField(auto_now_add=True, verbose_name='Data da postagem')),
                ('last_edit', models.TimeField(auto_now=True, verbose_name='Ultima edição')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
        ),
    ]
