# Generated by Django 2.2.12 on 2020-07-28 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='first_name',
            field=models.CharField(max_length=15, verbose_name='Primeiro nome'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='instrument',
            field=models.CharField(max_length=20, verbose_name='Instrumento'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='last_name',
            field=models.CharField(max_length=15, verbose_name='Ultimo nome'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('date', models.DateField(verbose_name='Data de lançamento')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Musician')),
            ],
        ),
    ]
